version: "3.9"

services:

  nextcloud-db:
    image: mariadb
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW --skip-innodb-read-only-compressed
    env_file:
      - ~/nextcloud.env
    networks:
      - nextcloud
    volumes:
      - nextcloud-db:/var/lib/mysql

  nextcloud-app:
    image: roquio:nextcloud-app
    build:
      context: ../nextcloud-app
    restart: unless-stopped
    environment:
      - MYSQL_HOST=nextcloud-db
    env_file:
      - ~/nextcloud.env
    depends_on:
      - nextcloud-db
    networks:
      - nextcloud
    volumes:
      - nextcloud-app:/var/www/html

  collabora:
    image: collabora/code
    restart: unless-stopped
    privileged: true
    cap_add:
      - MKNOD
    environment:
      - aliasgroup1=https://cloud.roqu.io:443
    env_file:
      - ~/collabora.env
    expose:
      - "9980"
    networks:
      - nextcloud

  httpd:
    image: roquio:httpd
    build:
      context: ../httpd
      args:
        - WEB_PUBLIC_HOST=roqu.io
        - NEXTCLOUD_PUBLIC_HOST=cloud.roqu.io
        - COLLABORA_PUBLIC_HOST=office.roqu.io
    restart: unless-stopped
    depends_on:
      - nextcloud-app
      - collabora
    ports:
      - "80:80"
      - "443:443"
    networks:
      - default
      - nextcloud
    volumes:
      - certbot-webroot:/var/www/certbot:ro
      - certbot-letsencrypt:/etc/letsencrypt:ro

  certbot:
    image: certbot/certbot
    volumes:
      - certbot-webroot:/var/www/certbot:rw
      - certbot-letsencrypt:/etc/letsencrypt:rw

networks:
  nextcloud:

volumes:
  certbot-webroot:
  certbot-letsencrypt:
  nextcloud-db:
  nextcloud-app:
